#!/usr/bin/env python3
"""
make_banks — slice several amen versions into 8 selectable banks for the slicer.
Each bank = one source's first bar chopped into 16 sixteenths. Writes
audio/bkNsMM.wav (8-bit mono) and generates include/banks.h (the C++ lookup
table + per-bank step timing). Run from the project root.

    tools/make_banks.py
"""
import subprocess, wave, os
import numpy as np
from PIL import Image, ImageDraw

RATE = 16000
FPS  = 59.7275                # real GBA refresh rate (NOT 60) — keeps tempo accurate for sync
BAR_GUESS = 1.74186           # ~137.8 BPM amen bar, used to auto-detect bar length
PACK = "/Users/ejfox/Library/Mobile Documents/com~apple~CloudDocs/Desktop/2025/2025-10/Rhythm Lab The Ultimate Amen Breaks Pack"

# (label, path, bar_seconds)  bar=None → auto-detect (~137 BPM). For retempo'd
# remixes the filename BPM gives the bar: bar = 240 / BPM.
BANKS = [
    ("clean",   f"{PACK}/Original/AmenVN_4barOrig.wav", None),
    ("winston", f"{PACK}/Original/Amen Break Unknown - The Winstons - Amen Brother.wav", None),
    ("45rpm",   f"{PACK}/Original/Amen Break Vinyl - Fanu Amen-from-the-45.wav", None),
    ("33rpm",   f"{PACK}/Original/amen-33.wav", None),
    ("cleaned", f"{PACK}/Original/Amen-cleaned a bit.wav", None),
    ("vinyl",   f"{PACK}/Original/Amen Break Vinyl - Fanu amen-7.wav", None),
    ("tape",    f"{PACK}/Fanu/AMEN-cassette 1.wav", None),
    ("2000xl",  f"{PACK}/Fanu/amen-2000xl-quieterer.wav", None),
    # --- weirder ---
    ("crush",   f"{PACK}/Fanu/amen-sonalksis-multilimit-comp.wav", None),
    ("soft",    f"{PACK}/Fanu/amen-2000xl-quietererer-SOFTEN.wav", None),
    ("freak",   f"{PACK}/SAMPLED AND REMIXED/170 Freak Break.wav", 240/170),
    ("skull",   f"{PACK}/SAMPLED AND REMIXED/165 Skull Break.wav", 240/165),
    ("toptape", f"{PACK}/SAMPLED AND REMIXED/150 TopTape Break.wav", 240/150),
]
SLICES, FADE = 16, 16
ENV_RES = 24                  # waveform-envelope resolution baked in for zen-mode viz
WAVE_W, WAVE_H = 64, 32        # per-bank waveform sprite (real audio, one frame each)

def duration(path):
    out = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                          "-of","csv=p=0", path], capture_output=True, text=True).stdout.strip()
    return float(out)

# wipe old slices
os.makedirs("audio", exist_ok=True)
for f in os.listdir("audio"):
    if f.endswith(".wav"): os.remove(os.path.join("audio", f))

steps, envs = [], []
wsheet = Image.new("RGBA", (WAVE_W, WAVE_H * len(BANKS)), (0, 0, 0, 0))   # waveform sprite sheet
wdraw  = ImageDraw.Draw(wsheet)
for bi, (label, path, barov) in enumerate(BANKS):
    dur  = duration(path)
    if barov:  bar = barov                              # explicit bar (retempo'd remixes)
    else:      bar = dur / max(1, round(dur / BAR_GUESS))  # auto-detect (~137 BPM)
    raw  = subprocess.run(["ffmpeg","-v","error","-t",str(bar),"-i",path,
                           "-ac","1","-ar",str(RATE),"-f","s16le","-"],
                          capture_output=True).stdout
    x = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    x = np.clip(x / max(1e-6, float(np.abs(x).max())) * 0.95, -1.0, 1.0)

    # waveform envelope: RMS of ENV_RES equal chunks of the bar, 0..255
    e = np.array([np.sqrt(np.mean(c**2)) if c.size else 0.0
                  for c in np.array_split(np.abs(x), ENV_RES)])
    e = np.clip(np.round(e / max(1e-6, e.max()) * 255), 0, 255).astype(int)
    envs.append(e)

    # draw this bank's real waveform into its frame of the sprite sheet
    cy0 = bi * WAVE_H + WAVE_H // 2
    for cx, col in enumerate(np.array_split(np.abs(x), WAVE_W)):
        h = int((col.max() if col.size else 0.0) * (WAVE_H // 2 - 1))
        wdraw.line([(cx, cy0 - h), (cx, cy0 + h)], fill=(255, 255, 255, 255))

    slen = x.size // SLICES
    for i in range(SLICES):
        c = x[i*slen:(i+1)*slen].copy()
        c[:FADE]  *= np.linspace(0, 1, FADE)
        c[-FADE:] *= np.linspace(1, 0, FADE)
        b = np.clip(np.round(128 + c * 120), 0, 255).astype(np.uint8).tobytes()
        w = wave.open(f"audio/bk{bi}s{i:02d}.wav", "wb")
        w.setnchannels(1); w.setsampwidth(1); w.setframerate(RATE); w.writeframes(b); w.close()
    fstep = slen / RATE * FPS                            # frames per 16th at the true refresh rate
    steps.append(fstep)
    print(f"  bank {bi} {label:8s}  bar={bar:.3f}s  slice={slen}  frames/step={fstep:.4f}  {15*RATE/slen:.1f}bpm")

# generate the C++ lookup table
os.makedirs("include", exist_ok=True)
with open("include/banks.h", "w") as h:
    h.write("// generated by tools/make_banks.py — do not edit by hand\n")
    h.write("#ifndef BANKS_H\n#define BANKS_H\n\n")
    h.write('#include "bn_fixed.h"\n#include "bn_sound_item.h"\n#include "bn_sound_items.h"\n\n')
    h.write("namespace banks\n{\n")
    h.write(f"    constexpr int COUNT = {len(BANKS)};\n\n")
    h.write("    inline const bn::sound_item* slices[COUNT][16] = {\n")
    for bi, _ in enumerate(BANKS):
        row = ", ".join(f"&bn::sound_items::bk{bi}s{i:02d}" for i in range(SLICES))
        h.write(f"        {{ {row} }},\n")
    h.write("    };\n\n")
    h.write("    inline const bn::fixed step[COUNT] = { "
            + ", ".join(f"bn::fixed({s:.4f})" for s in steps) + " };\n")
    h.write("    inline const char* name[COUNT] = { "
            + ", ".join(f'"{lbl}"' for lbl, *_ in BANKS) + " };\n\n")
    h.write(f"    constexpr int ENV_RES = {ENV_RES};\n")
    h.write("    inline const unsigned char env[COUNT][ENV_RES] = {\n")
    for e in envs:
        h.write("        { " + ", ".join(str(v) for v in e) + " },\n")
    h.write("    };\n")
    h.write("}\n\n#endif\n")

# waveform sprite sheet -> BMP for grit
wsheet.save("art/waves.png")
subprocess.run(["python3", "tools/png2bmp.py", "art/waves.png", "graphics/waves.bmp"], check=True)
with open("graphics/waves.json", "w") as j:
    j.write('{\n    "type": "sprite",\n    "height": 32\n}\n')

print(f"wrote {len(BANKS)*SLICES} slices + include/banks.h + graphics/waves.bmp ({len(BANKS)} frames)")
