#!/usr/bin/env python3
"""
make_banks — slice several amen versions into 8 selectable banks for the slicer.
Each bank = one source's first bar chopped into 16 sixteenths. Writes
audio/bkNsMM.wav (8-bit mono) and generates include/banks.h (the C++ lookup
table + per-bank step timing). Run from the project root.

    tools/make_banks.py
"""
import subprocess, wave, os
import numpy as np

RATE = 16000
BAR_GUESS = 1.74186           # ~137.8 BPM amen bar, used to auto-detect bar length
PACK = "/Users/ejfox/Library/Mobile Documents/com~apple~CloudDocs/Desktop/2025/2025-10/Rhythm Lab The Ultimate Amen Breaks Pack"

# (label shown in-game, path) — 8 tonal flavors
BANKS = [
    ("clean",   f"{PACK}/Original/AmenVN_4barOrig.wav"),
    ("winston", f"{PACK}/Original/Amen Break Unknown - The Winstons - Amen Brother.wav"),
    ("45rpm",   f"{PACK}/Original/Amen Break Vinyl - Fanu Amen-from-the-45.wav"),
    ("33rpm",   f"{PACK}/Original/amen-33.wav"),
    ("cleaned", f"{PACK}/Original/Amen-cleaned a bit.wav"),
    ("vinyl",   f"{PACK}/Original/Amen Break Vinyl - Fanu amen-7.wav"),
    ("tape",    f"{PACK}/Fanu/AMEN-cassette 1.wav"),
    ("2000xl",  f"{PACK}/Fanu/amen-2000xl-quieterer.wav"),
]
SLICES, FADE = 16, 16

def duration(path):
    out = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                          "-of","csv=p=0", path], capture_output=True, text=True).stdout.strip()
    return float(out)

# wipe old slices
os.makedirs("audio", exist_ok=True)
for f in os.listdir("audio"):
    if f.endswith(".wav"): os.remove(os.path.join("audio", f))

steps = []
for bi, (label, path) in enumerate(BANKS):
    dur  = duration(path)
    bars = max(1, round(dur / BAR_GUESS))
    bar  = dur / bars                                   # first bar length (seconds)
    raw  = subprocess.run(["ffmpeg","-v","error","-t",str(bar),"-i",path,
                           "-ac","1","-ar",str(RATE),"-f","s16le","-"],
                          capture_output=True).stdout
    x = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    x = np.clip(x / max(1e-6, float(np.abs(x).max())) * 0.95, -1.0, 1.0)
    slen = x.size // SLICES
    for i in range(SLICES):
        c = x[i*slen:(i+1)*slen].copy()
        c[:FADE]  *= np.linspace(0, 1, FADE)
        c[-FADE:] *= np.linspace(1, 0, FADE)
        b = np.clip(np.round(128 + c * 120), 0, 255).astype(np.uint8).tobytes()
        w = wave.open(f"audio/bk{bi}s{i:02d}.wav", "wb")
        w.setnchannels(1); w.setsampwidth(1); w.setframerate(RATE); w.writeframes(b); w.close()
    fps = slen / RATE * 60                               # frames per step @60fps
    steps.append(fps)
    print(f"  bank {bi} {label:8s}  {bars}bar  slice={slen}  frames/step={fps:.4f}  ~{900/fps:.0f}bpm")

# generate the C++ lookup table
os.makedirs("include", exist_ok=True)
with open("include/banks.h", "w") as h:
    h.write("// generated by tools/make_banks.py — do not edit by hand\n")
    h.write("#ifndef BANKS_H\n#define BANKS_H\n\n")
    h.write('#include "bn_fixed.h"\n#include "bn_sound_item.h"\n#include "bn_sound_items.h"\n\n')
    h.write("namespace banks\n{\n")
    h.write(f"    constexpr int COUNT = {len(BANKS)};\n\n")
    h.write("    inline const bn::sound_item* slices[COUNT][16] = {\n")
    for bi, _ in enumerate(BANKS):
        row = ", ".join(f"&bn::sound_items::bk{bi}s{i:02d}" for i in range(SLICES))
        h.write(f"        {{ {row} }},\n")
    h.write("    };\n\n")
    h.write("    inline const bn::fixed step[COUNT] = { "
            + ", ".join(f"bn::fixed({s:.4f})" for s in steps) + " };\n")
    h.write("    inline const char* name[COUNT] = { "
            + ", ".join(f'"{lbl}"' for lbl, _ in BANKS) + " };\n")
    h.write("}\n\n#endif\n")

print(f"wrote {len(BANKS)*SLICES} slices + include/banks.h")
