// AMEN SLICER — a breakbeat slicer for GBA.
// 8 real amen versions, each sliced into 16 sixteenths. Repitch + stutter live.
#include "pk.h"
#include "banks.h"                 // generated by tools/make_banks.py

#include "bn_optional.h"
#include "bn_string.h"
#include "bn_sound_items.h"

namespace
{
    constexpr int STEPS = 16;

    bn::fixed speed = 1;
    bn::fixed acc   = 0;
    int step  = 0;
    int bank  = 0;
    int flash = 0;
    int upd   = 0, dnd = 0;                 // build/tape-stop ramp counters

    bn::vector<pk::Circle, STEPS> dots;
    bn::optional<pk::Circle>      vu;
    bn::optional<pk::Text>        hud;

    // A=1/16  B=1/32  L=1/8  R=1/64  (checked fastest-first so it wins if multiple held)
    bn::fixed repeat_mult()
    {
        if(pk::down(pk::key::R)) return bn::fixed(0.25); // 1/64
        if(pk::down(pk::key::B)) return bn::fixed(0.5);  // 1/32
        if(pk::down(pk::key::A)) return 1;               // 1/16
        if(pk::down(pk::key::L)) return 2;               // 1/8
        return 0;
    }
    const char* repeat_name()
    {
        if(pk::down(pk::key::R)) return "1/64";
        if(pk::down(pk::key::B)) return "1/32";
        if(pk::down(pk::key::A)) return "1/16";
        if(pk::down(pk::key::L)) return "1/8";
        return "off";
    }
}

void pk::setup()
{
    background(vulpes::bg);
    hud.emplace();
    vu.emplace();
    vu->fill(vulpes::base);
    for(int i = 0; i < STEPS; ++i) { dots.emplace_back(); dots[i].pos(col(i, STEPS), -26); }
}

void pk::update()
{
    fixed rmult     = repeat_mult();
    bool  repeating = rmult > 0;                      // any stutter button held?

    // pitch + step-rate for playback; the d-pad modulates these while stuttering
    fixed fxpitch = speed, fxrate = speed;
    if(repeating)
    {
        // HOLD A STUTTER + ARROWS = stacked breakdown FX
        if(down(key::UP))   { upd = upd + 1 > 90 ? 90 : upd + 1;               // accelerating BUILD
                              fixed r = 1 + fixed(upd) * fixed(0.03); fxpitch = speed * r; fxrate = speed * r; }
        else                  upd = 0;
        if(down(key::DOWN)) { dnd = dnd + 1 > 90 ? 90 : dnd + 1;               // TAPE STOP (slow + drop)
                              fixed r = clamp(1 - fixed(dnd) * fixed(0.012), fixed(0.2), fixed(1)); fxpitch = speed * r; fxrate = speed * r; }
        else                  dnd = 0;
        if(down(key::RIGHT))  fxpitch = fxpitch * fixed(1.5);                  // pitch UP (hype)
        if(down(key::LEFT))   fxpitch = fxpitch * fixed(0.6);                  // pitch DOWN (screw)
    }
    else
    {
        upd = 0; dnd = 0;
        if(down(key::UP))       speed = clamp(speed + fixed(0.015), fixed(0.4), fixed(2.5));  // stretch
        if(down(key::DOWN))     speed = clamp(speed - fixed(0.015), fixed(0.4), fixed(2.5));
        if(pressed(key::RIGHT)) { bank = (bank + 1) % banks::COUNT; acc = 0; }                // flavor
        if(pressed(key::LEFT))  { bank = (bank + banks::COUNT - 1) % banks::COUNT; acc = 0; }
    }
    if(pressed(key::SELECT)) { bank = (bank + 1) % banks::COUNT; acc = 0; }    // flavor also on SELECT

    fixed interval = (repeating ? banks::step[bank] * rmult : banks::step[bank]) / fxrate;

    // START = jump straight to the 1 (downbeat) and hit it this frame
    if(pressed(key::START)) { step = 0; acc = interval; }

    // clock — trigger a slice when the accumulator crosses the step
    acc += 1;
    if(acc >= interval)
    {
        acc -= interval;
        bool downbeat = (step == 0);
        banks::slices[bank][step]->play(repeating ? fixed(0.7) : fixed(0.9),
                                        clamp(fxpitch, fixed(0.1), fixed(6)), 0);
        flash = downbeat ? 8 : 4;                    // bigger pulse on the 1
        if(! repeating) step = (step + 1) % STEPS;   // stutter freezes the current slice
    }
    if(flash > 0) --flash;

    // ---- visuals (step 0 is marked as the downbeat) ----
    for(int i = 0; i < STEPS; ++i)
        dots[i].radius(i == step ? 6 : (i == 0 ? 4 : 2));
    vu->pos(0, -2).radius(flash > 0 ? map(fixed(flash), 0, 8, 5, 18) : 5);

    // BPM = native tempo of this flavor, scaled by stretch  (900 / frames-per-16th)
    int bpm = (fixed(900) * speed / banks::step[bank] + fixed(0.5)).integer();

    // active breakdown FX (arrows while stuttering)
    const char* brk = "";
    if(repeating)
    {
        if(down(key::UP))         brk = " build";
        else if(down(key::DOWN))  brk = " stop";
        else if(down(key::RIGHT)) brk = " up";
        else if(down(key::LEFT))  brk = " down";
    }

    // ---- self-explaining control panel ----
    hud->clear();
    hud->align_center();
    hud->print(0, -64, "AMEN SLICER");
    hud->print(0,  14, bn::string<32>("< ") + banks::name[bank] + " >   "
                        + bn::to_string<8>(bpm) + " BPM");
    hud->print(0,  32, "UP/DN speed    START = 1");
    hud->print(0,  48, bn::string<32>("SEL flavor   FX ") + repeat_name() + brk);
    hud->print(0,  63, "stutter+arrows A16 B32 L8 R64");
    hud->tint(vulpes::teal);
}

int main() { pk::run(); }
