// AMEN SLICER — a breakbeat slicer for Game Boy Advance (Butano + the pk layer).
// 13 real amen versions, each chopped into 16 sixteenth-notes, on a sync-locked
// clock with a reactive visualizer. Atomic-purple theme on OLED black.
//
// CONTROLS
//   Up / Down          tempo / stretch (repitch; live BPM readout)
//   Left / Right        previous / next flavor
//   A / B / L / R       stutter 1/16, 1/32, 1/8, 1/64 (hold)
//   hold stutter + arrow  breakdown FX — Up=build, Down=tape-stop, L/R=pitch
//   START               tap the loop back to the 1 (align to an external downbeat)
//   SELECT              toggle EXPLAIN <-> ZEN view
//   SELECT + START      toggle CRUSH (downsample / bitcrush FX)
//
// ZEN combos: A+B = + signs, L+R = inside-out, A+B+L+R = chaos. Downbeats & drops
// fire shockwaves; a tape-stop freezes the whole visual with the audio.
#include "pk.h"
#include "banks.h"

#include "bn_optional.h"
#include "bn_string.h"
#include "bn_sound_items.h"
#include "bn_sound_handle.h"
#include "bn_sprite_items_waves.h"      // real per-bank waveform (generated by make_banks.py)

namespace T = pk::atomic;

namespace
{
    using pk::fixed; using pk::color;
    constexpr int STEPS = 16, NP = 16, TRAIL = 5, RES = banks::ENV_RES, SHOCKN = 12;
    constexpr fixed BPM_K = fixed(895.9);

    fixed speed = 1, acc = 0, sacc = 0, rot = 0, rot2 = 0;
    int step = 0, froz = 0, bank = 0, upd = 0, dnd = 0;
    bool zen = false, wasRep = false, wasCombo = false, peaked = false, crush = false;

    fixed vspeed = 1, vstut = 0, vpitch = 1, flashF = 0, vmotion = 1, venv[RES] = { 0 };
    pk::Spring zoom;
    bn::vector<bn::sprite_ptr, 4> wsp;   // full-width waveform = 4 x 64px segments
    int waveBank = -1;

    // BIG IMPACTS: an expanding shockwave ring + a screen flash
    fixed shockR = 0, shockSpd = 0; bool shockOn = false; int bgflash = 0;

    bn::optional<pk::Circle>      vu;         // explain: playhead over the waveform
    bn::vector<pk::Circle, RES>   ring, ring2;
    bn::vector<pk::Circle, TRAIL> comet;
    bn::vector<pk::Circle, NP>    parts;
    bn::vector<pk::Circle, SHOCKN> shock;
    bn::optional<pk::Circle>      core;
    pk::Body pbody[NP];
    int      plife[NP] = { 0 };
    bn::optional<pk::Text> hud;
    bn::optional<bn::sound_handle> voice;

    fixed repeat_mult()
    {
        if(pk::down(pk::key::R)) return fixed(0.25);
        if(pk::down(pk::key::B)) return fixed(0.5);
        if(pk::down(pk::key::A)) return 1;
        if(pk::down(pk::key::L)) return 2;
        return 0;
    }
    const char* repeat_name()
    {
        if(pk::down(pk::key::R)) return "1/64";
        if(pk::down(pk::key::B)) return "1/32";
        if(pk::down(pk::key::A)) return "1/16";
        if(pk::down(pk::key::L)) return "1/8";
        return "off";
    }

    color mix(color a, color b, fixed t)
    {
        t = pk::clamp(t, fixed(0), fixed(1));
        auto L = [&](int x, int y) { return (fixed(x) + fixed(y - x) * t).integer(); };
        return color(L(a.red(), b.red()), L(a.green(), b.green()), L(a.blue(), b.blue()));
    }

    void fire(fixed spd, int flsh) { shockR = 0; shockSpd = spd; shockOn = true; bgflash = flsh; zoom.vel += spd / 22; }

    void build_explain()
    {
        ring.clear(); ring2.clear(); comet.clear(); parts.clear(); shock.clear(); core.reset();
        vu.emplace(); vu->fill(T::base);
    }
    void build_zen()
    {
        vu.reset();
        ring.clear();  for(int i = 0; i < RES; ++i)    ring.emplace_back();
        ring2.clear(); for(int i = 0; i < RES; ++i)    ring2.emplace_back();
        comet.clear(); for(int i = 0; i < TRAIL; ++i)  comet.emplace_back();
        parts.clear(); for(int i = 0; i < NP; ++i)   { parts.emplace_back(); parts[i].show(false); plife[i] = 0; }
        shock.clear(); for(int i = 0; i < SHOCKN; ++i){ shock.emplace_back(); shock[i].show(false); }
        core.emplace(); core->fill(T::base);
        zoom.reset(1); zoom.stiffness = fixed(0.22); zoom.damping = fixed(0.6); shockOn = false;
        for(int i = 0; i < RES; ++i) venv[i] = fixed(banks::env[bank][i]) / 255;
    }

    void spawn_burst(int st, bool downbeat)
    {
        fixed amp = fixed(banks::env[bank][st * RES / STEPS]) / 255;
        int n = downbeat ? 8 : 3;
        for(int c = 0; c < n; ++c)
            for(int i = 0; i < NP; ++i)
                if(plife[i] <= 0)
                {
                    fixed a = pk::rnd(0, 360), spd = pk::rnd(fixed(1), fixed(3)) * (fixed(0.6) + amp);
                    fixed tang = pk::rnd(fixed(-2), fixed(2));
                    pbody[i] = { 0, 0, pk::cos(a) * spd - pk::sin(a) * tang,
                                       pk::sin(a) * spd + pk::cos(a) * tang };
                    plife[i] = 18 + (amp * 14).integer();
                    break;
                }
    }
}

void pk::setup()
{
    background(T::bg);
    hud.emplace();
    for(int s = 0; s < 4; ++s) { wsp.push_back(bn::sprite_items::waves.create_sprite(-96 + s * 64, -24, s)); wsp[s].set_z_order(3); }
    build_explain();
}

void pk::update()
{
    // ---- controls ----
    fixed rmult = repeat_mult();
    bool  repeating = rmult > 0;
    fixed fxpitch = speed;

    if(repeating)
    {
        if(down(key::UP))   upd = upd + 1 > 90 ? 90 : upd + 1; else upd = 0;
        if(down(key::DOWN)) dnd = dnd + 1 > 90 ? 90 : dnd + 1; else dnd = 0;
        fxpitch = speed * (1 + fixed(upd) * fixed(0.03));
        if(down(key::RIGHT)) fxpitch = fxpitch * fixed(1.5);
        if(down(key::LEFT))  fxpitch = fxpitch * fixed(0.6);
    }
    else
    {
        upd = 0; dnd = 0;
        if(down(key::UP))       speed = clamp(speed + fixed(0.01), fixed(0.4), fixed(2.5));
        if(down(key::DOWN))     speed = clamp(speed - fixed(0.01), fixed(0.4), fixed(2.5));
        if(pressed(key::RIGHT)) { bank = (bank + 1) % banks::COUNT; zoom.vel += fixed(0.3); }
        if(pressed(key::LEFT))  { bank = (bank + banks::COUNT - 1) % banks::COUNT; zoom.vel += fixed(0.3); }
    }

    if(pressed(key::SELECT) && down(key::START)) crush = ! crush;   // SEL+START chord = downsample FX
    else if(pressed(key::SELECT)) { zen = ! zen; if(zen) build_zen(); else build_explain(); zoom.vel += fixed(0.5); }

    // ---- WILD combos (visual; audio still stutters underneath) ----
    bool cPlus  = down(key::A) && down(key::B);      // circles -> + signs
    bool cInv   = down(key::L) && down(key::R);      // mandala turns inside-out
    bool cChaos = cPlus && cInv;                     // everything at once
    bool combo  = cPlus || cInv;
    if(combo && ! wasCombo && zen) fire(14, 6);      // transformation punch
    wasCombo = combo;

    fixed masterInterval = banks::step[bank] / speed;

    if(pressed(key::START) && ! down(key::SELECT)) { step = 0; acc = 0; sacc = 0; flashF = 1; fire(16, 9); }   // slam to the 1

    if(repeating && ! wasRep) froz = step;
    wasRep = repeating;
    bool stopping = repeating && down(key::DOWN);

    // motion factor — when the audio halts (tape-stop), the WHOLE visual freezes with it
    fixed targetMotion = stopping ? ((voice && voice->active()) ? clamp(voice->speed(), fixed(0), fixed(1)) : fixed(0)) : fixed(1);
    vmotion = approach(vmotion, targetMotion, fixed(0.25));

    // ---- MASTER CLOCK (motion-gated → the sequencer freezes with the audio) ----
    bool masterTick = false;
    acc += vmotion;
    if(acc >= masterInterval) { acc -= masterInterval; step = (step + 1) % STEPS; masterTick = true; }

    bool downbeat = false;
    fixed subphase = 0;
    auto hitv = [&](int idx)
    {
        voice = (crush ? banks::slicesC : banks::slices)[bank][idx]->play(repeating ? fixed(0.7) : fixed(0.9), clamp(fxpitch, fixed(0.1), fixed(6)), 0);
        downbeat = (idx == 0);
        flashF = downbeat ? 1 : fixed(0.6);
        if(zen) { spawn_burst(idx, downbeat); zoom.vel += downbeat ? fixed(0.6) : fixed(0.28); if(downbeat) fire(8, 3); }
    };

    if(stopping)
    {
        if(voice && voice->active()) voice->set_speed(clamp(voice->speed() * fixed(0.9), fixed(0.02), fixed(6)));
        sacc = 0;
    }
    else if(repeating)
    {
        fixed stutInterval = masterInterval * rmult / (1 + fixed(upd) * fixed(0.04));
        sacc += 1;
        if(sacc >= stutInterval) { sacc -= stutInterval; hitv(froz); }
        subphase = clamp(sacc / stutInterval, fixed(0), fixed(1));   // 0..1 across the frozen slice
    }
    else { sacc = 0; if(masterTick) hitv(step); }

    // build peak = THE DROP → mega impact
    if(upd >= 90 && ! peaked) { peaked = true; if(zen) fire(22, 12); }
    if(upd < 90) peaked = false;

    // ---- eased visual system ----
    vspeed = approach(vspeed, speed, fixed(0.08));
    fixed stutTarget = repeating ? clamp(map(rmult, 2, fixed(0.25), fixed(0.3), 1), fixed(0.3), 1) : fixed(0);
    vstut  = approach(vstut, stutTarget, fixed(0.12));
    vpitch = approach(vpitch, fxpitch, fixed(0.1));
    flashF = approach(flashF, 0, fixed(0.16));
    if(vmotion > fixed(0.1))
        for(int i = 0; i < RES; ++i) venv[i] = approach(venv[i], fixed(banks::env[bank][i]) / 255, fixed(0.09));

    if(bank != waveBank) { for(int s = 0; s < 4; ++s) wsp[s].set_item(bn::sprite_items::waves, bank * 4 + s); waveBank = bank; }

    int bpm = (BPM_K * speed / banks::step[bank] + fixed(0.5)).integer();

    fixed drift = (sin(fixed(frame) * fixed(1.4)) + 1) / 2;
    color c = mix(T::base, T::bright, drift);
    c = mix(c, T::glow, flashF);
    c = mix(c, T::cyan, clamp(vstut * fixed(0.7) + fixed(upd) / 120, fixed(0), fixed(0.9)));
    c = mix(c, T::dim,  fixed(dnd) / 100);
    c = mix(c, vpitch > 1 ? T::glow : T::deep, clamp((vpitch > 1 ? vpitch - 1 : 1 - vpitch) * fixed(0.5), fixed(0), fixed(0.4)));
    if(cChaos)     c = ((frame / 3) % 2 == 0) ? T::cyan : T::glow;    // hard strobe
    else if(cPlus) c = mix(c, T::glow, fixed(0.5));

    // playhead position: normally sweeps the loop; while repeating it LOOPS the
    // frozen slice (visualizes the repeat instead of advancing).
    fixed vizphase = repeating ? (fixed(froz) + subphase) / STEPS
                               : (fixed(step) + acc / masterInterval) / STEPS;
    fixed playx = map(vizphase, 0, 1, -120, 120);

    // screen flash on impacts (both modes)
    if(bgflash > 0) --bgflash;
    background(bgflash > 0 ? mix(T::bg, T::glow, fixed(bgflash) / 12) : T::bg);

    if(zen)
    {
        bool P = cPlus || cChaos, I = cInv || cChaos;
        fixed zp = vmotion > fixed(0.05) ? zoom.update(1) : zoom.pos;   // freeze the breathe when stopped
        fixed Z = clamp(zp, fixed(0.4), fixed(2)) * (1 - vstut * fixed(0.15));
        rot  += (fixed(0.3) + vspeed * fixed(0.5) + vstut * fixed(0.8) + fixed(upd) * fixed(0.06) - fixed(dnd) * fixed(0.05) + (cChaos ? fixed(7) : fixed(0))) * vmotion;
        rot2 -= (fixed(0.5) + vspeed * fixed(0.35) + vstut * fixed(0.5) + (cChaos ? fixed(9) : fixed(0))) * vmotion;
        fixed scale = fixed(0.85) + vpitch * fixed(0.15);

        for(int i = 0; i < RES; ++i)
        {
            fixed eo = venv[i], ei = venv[RES - 1 - i];
            fixed Ro = I ? (64 - (30 + eo * 28)) : (30 + eo * 28);        // invert = inside-out
            fixed Ri = I ? (40 - (12 + ei * 14)) : (12 + ei * 14);
            fixed ao = fixed(i) * 360 / RES + rot, ai = fixed(i) * 360 / RES + rot2;
            ring [i].plus(P).pos(cos(ao) * Ro * Z * scale, sin(ao) * Ro * Z * scale).diameter(2 + eo * 5);
            ring2[i].plus(P).pos(cos(ai) * Ri * Z * scale, sin(ai) * Ri * Z * scale).diameter(1 + ei * 3);
        }
        fixed ca = vizphase * 360 + rot, cr = 62 * Z * scale;   // comet loops the frozen slice while repeating
        for(int k = 0; k < TRAIL; ++k)
        { fixed ka = ca - fixed(k) * 9; comet[k].plus(P).pos(cos(ka) * cr, sin(ka) * cr).diameter(7 - k); }

        core->plus(P).pos(0, 0).diameter(map(flashF, 0, 1, 5 * Z, 22)).fill(c);
        for(int i = 0; i < NP; ++i)
        {
            if(plife[i] > 0) { pbody[i].kick(-pbody[i].x * fixed(0.01) * vmotion, -pbody[i].y * fixed(0.01) * vmotion);
                               pbody[i].damp(fixed(0.95));
                               pbody[i].x += pbody[i].vx * vmotion; pbody[i].y += pbody[i].vy * vmotion;  // motion-gated
                               if(vmotion > fixed(0.1)) --plife[i];
                               parts[i].plus(P).pos(pbody[i].x, pbody[i].y).diameter(map(fixed(plife[i]), 0, 28, 1, 6)).show(true); }
            else             parts[i].show(false);
        }

        // shockwave ring
        if(shockOn)
        {
            shockR += shockSpd * vmotion;
            for(int i = 0; i < SHOCKN; ++i)
            {
                fixed a = fixed(i) * 360 / SHOCKN;
                shock[i].plus(P).pos(cos(a) * shockR, sin(a) * shockR)
                        .diameter(clamp(fixed(9) - shockR / 16, fixed(1), fixed(9))).show(true);
            }
            if(shockR > 150) shockOn = false;
        }
        else for(int i = 0; i < SHOCKN; ++i) shock[i].show(false);

        for(int s = 0; s < 4; ++s) wsp[s].set_visible(false);   // no waveform in zen — mandala only

        hud->clear();
        hud->align_center();
        hud->print(0, 68, bn::string<24>(banks::name[bank]) + "   " + bn::to_string<8>(bpm) + " BPM");
        hud->align_right();
        hud->print(right - 4, top + 4, "SEL=info");
        hud->tint(mix(T::dim, T::bright, drift));
    }
    else
    {
        // full-width waveform; playhead sweeps it, or loops the frozen slice on a repeat
        { bn::sprite_palette_ptr wp = wsp[0].palette(); wp.set_fade(T::base, 1); }
        for(int s = 0; s < 4; ++s) { wsp[s].set_position(-96 + s * 64, -26); wsp[s].set_visible(true); }
        vu->pos(playx, -26).radius(map(flashF, 0, 1, 4, 11)).fill(c);

        const char* brk = "";
        if(repeating) { if(down(key::UP)) brk = " build"; else if(down(key::DOWN)) brk = " stop";
                        else if(down(key::RIGHT)) brk = " up"; else if(down(key::LEFT)) brk = " down"; }

        bn::string<48> l2 = bn::string<48>("< ") + banks::name[bank] + " >  " + bn::to_string<8>(bpm) + " BPM";
        if(repeating) l2 = l2 + "  " + repeat_name() + brk;
        if(crush)     l2 = l2 + "  CRUSH";

        hud->clear();
        hud->align_center();
        hud->print(0, -50, "AMEN SLICER");
        hud->print(0,  26, l2);
        hud->print(0,  42, "UP/DN spd  L/R flav  ST=1");
        hud->print(0,  58, "A16 B32 L8 R64  SEL+ST=crush");
        hud->align_right();
        hud->print(right - 4, top + 4, "SEL=zen");
        hud->tint(T::fg);
    }
}

int main() { pk::run(); }
